In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot
import os
from astropy import units as u
from astropy.coordinates import SkyCoord

In [2]:
# SS_LCs = pd.read_csv("https://cdsarc.cds.unistra.fr/ftp/J/AJ/155/201/table8.dat", sep = "\\s+|\\||\\|s",
#                      names = ["Name","MJD","Phase","Filter","Mag","Mag Error","Flux","Flux Error"])
SS_LCs = pd.read_fwf("https://cdsarc.cds.unistra.fr/ftp/J/AJ/155/201/table8.dat",
                     names = ["Name","MJD","Phase","Filter","Mag","Mag Error","Flux","Flux Error"],
                    colspecs = [[0,23],[24,35],[37,45],[46,52],[53,61],[62,69],[71,81],[83,92]])
SS_LCs

,Name,MJD,Phase,Filter,Mag,Mag Error,Flux,Flux Error
0,CSS121009:011101-172841,56234.27359,14.27359,WHIRCJ,18.97756,0.05157,256.4340,12.1698
1,CSS121009:011101-172841,56229.31361,9.31361,WHIRCH,18.64361,0.04781,348.7850,15.3479
2,CSS121009:011101-172841,56229.28541,9.28541,WHIRCJ,19.27324,0.07101,195.3014,12.7551
3,CSS121009:011101-172841,56234.22657,14.22657,WHIRCH,18.53778,0.04162,384.4939,14.7330
4,CSS121114:090202+101800,56254.50847,2.50847,WHIRCH,18.08766,0.02963,582.0156,15.8819
...,...,...,...,...,...,...,...,...
181,iPTF13ebh,56640.15049,21.15049,WHIRCJ,16.22341,0.01276,3240.6910,38.0783
182,iPTF13ebh,56617.15312,-1.84688,WHIRCK,15.39068,0.01739,6977.9267,111.7250
183,iPTF13ebh,56636.16017,17.16017,WHIRCK,15.48230,0.07114,6413.2790,419.6413
184,iPTF13ebh,56640.15936,21.15936,WHIRCK,15.45387,0.01509,6583.4459,91.4833
185,iPTF13ebh,56617.13733,-1.86267,WHIRCH,15.47307,0.01356,6468.0416,80.7895

In [3]:
SS_LCs["Mag"].dtype

dtype('float64')

In [4]:
SS_info = pd.read_fwf("https://cdsarc.cds.unistra.fr/ftp/J/AJ/155/201/table3.dat", 
                      names = ["Name","RA","Dec","SN Type","z","Classifier","Discoverer","Tmax","Has LC?"],
                      colspecs = [[0,23],[24,36],[37,49],[50,52],[54,61],[63,74],[75,81],[81,86],[87,90]]                                                                      )
SS_info

,Name,RA,Dec,SN Type,z,Classifier,Discoverer,Tmax,Has LC?
0,CSS121006:232854+085452,23 28 54.48,+08 54 51.6,Ia,0.0800,D12b,D12c,56207,Yes
1,CSS121009:011101-172841,01 11 01.091,-17 28 42.28,Ia,0.0600,D12b,D12c,56220,Yes
2,CSS121114:090202+101800,09 02 02.420,+10 18 00.31,Ia,0.0420,G12,D12a,56252,Yes
3,CSS130218:092354+385837,09 23 54.52,+38 58 36.8,Ia,0.0500,D13b,D13a,56361,No
4,CSS130317:082848+293031,08 28 47.784,+29 30 30.85,Ia,0.0800,D13b,D13b,56370,No
...,...,...,...,...,...,...,...,...,...
69,iPTF13dge,05 03 35.091,+01 34 17.03,Ia,0.0158,C13b,C13b,56555,No
70,iPTF13dkj,23 08 50.737,+20 04 08.59,Ia,0.0300,C13a,C13a,56555,No
71,iPTF13dkl,23 44 57.999,+03 23 40.07,Ia,0.0400,C13a,C13a,56556,Yes
72,iPTF13dkx,01 20 53.115,+03 20 23.65,Ia,0.0300,C13a,C13a,56561,Yes
73,iPTF13ebh,02 21 59.98,+33 16 13.7,Ia,0.0132,C13c,C13c,56619,Yes

In [5]:
c1 =SS_info[SS_info["Name"]=="SN 2011fs"]["RA"]
c2 = SS_info[SS_info["Name"]=="SN 2011fs"]["Dec"]

In [6]:
c = SkyCoord(c1,c2,unit=(u.hourangle, u.deg))

In [7]:
c.ra.deg[0]

np.float64(334.3312875)

In [8]:
RA_degs = []
Dec_degs = []
New_name = []
for i in range(len(SS_info["Name"])):
    c1 = SS_info["RA"][i]
    c2 = SS_info["Dec"][i]
    c = SkyCoord(c1,c2,unit=(u.hourangle, u.deg))
    RA_degs.append(c.ra.deg)
    Dec_degs.append(c.dec.deg)
SS_info["RA_deg"] = RA_degs
SS_info["Dec_deg"] = Dec_degs

In [9]:
SS_info = SS_info[SS_info["Has LC?"] == "Yes"]

In [10]:
SS_info = SS_info.reset_index(drop = True)

In [11]:
SS_info

,Name,RA,Dec,SN Type,z,Classifier,Discoverer,Tmax,Has LC?,RA_deg,Dec_deg
0,CSS121006:232854+085452,23 28 54.48,+08 54 51.6,Ia,0.0800,D12b,D12c,56207,Yes,352.227000,8.914333
1,CSS121009:011101-172841,01 11 01.091,-17 28 42.28,Ia,0.0600,D12b,D12c,56220,Yes,17.754546,-17.478411
2,CSS121114:090202+101800,09 02 02.420,+10 18 00.31,Ia,0.0420,G12,D12a,56252,Yes,135.510083,10.300086
3,LSQ12fhs,22 52 23.423,-20 36 53.35,91,0.0330,CO12,CO12,56215,Yes,343.097596,-20.614819
4,LSQ12fmx,03 12 52.144,-00 12 12.55,Ia,0.0670,BN12,BN12,56227,Yes,48.217267,-0.203486
5,LSQ13cmt,01 02 41.95,-21 52 23.4,Ia,0.0570,CT13,CT13,56575,Yes,15.674792,-21.873167
6,LSQ13cwp,04 03 50.662,-02 39 18.57,Ia,0.0670,WK13,WK13,56606,Yes,60.961092,-2.655158
7,PS1-13dkh,03 11 16.09,+15 42 58.3,91,0.0300,Fo13,Fo13,56572,Yes,47.817042,15.716194
8,PTF11moy,17 06 18.06,+38 32 19.9,Ia,0.0600,GY11a,GY11a,55824,Yes,256.575250,38.538861
9,PTF11qmo,10 06 49.748,-07 41 12.39,Ia,0.0550,GY11b,GY11b,55894,Yes,151.707283,-7.686775
10,PTF11qri,12 47 06.276,-06 19 49.46,Ia,0.0550,GY11b,GY11b,55897,Yes,191.776150,-6.330406
11,PTF13asv,16 22 43.19,+18 57 35.0,Ia,0.0350,C13d,C13d,56423,Yes,245.679958,18.959722
12,PTF13dad,01 48 08.39,+37 33 29.1,Ia,0.0860,C13e,C13e,56547,Yes,27.034958,37.558083
13,PTF13ddg,00 47 50.83,+31 49 17.5,Ia,0.0840,C13e,C13e,56545,Yes,11.961792,31.821528
14,SN 2011fe,14 03 05.80,+54 16 25.3,Ia,0.0080,Nu11,Nu11,55814,Yes,210.774167,54.273694
15,SN 2011fs,22 17 19.509,+35 34 49.94,Ia,0.0210,BM11 To11b,J11a,55833,Yes,334.331287,35.580539
16,SN 2011gf,21 12 24.302,-07 48 52.04,Ia,0.0270,V11 M11,D11,55827,Yes,318.101258,-7.814456
17,SN 2011io,23 02 47.617,+08 48 08.12,Ia,0.0400,Fr11,Ba11,55894,Yes,345.698404,8.802256
18,SN 2011iy,13 08 58.38,-15 31 04.0,Ia,0.0042,CJ11 Y11,I11,55896,Yes,197.243250,-15.517778
19,SN 2011jh,12 47 14.42,-10 03 47.2,Ia,0.0077,To11a,NN11,55929,Yes,191.810083,-10.063111
20,SN 2012bh,12 13 37.325,+46 29 00.34,Ia,0.0252,CK12,CK12,56016,Yes,183.405521,46.483428
21,SN 2012bo,12 50 45.215,-14 16 07.69,Ia,0.0254,Ca12b DT12,I12,56021,Yes,192.688396,-14.268803
22,SN 2012bp,16 18 12.451,+36 28 51.87,Ia,0.0282,Pa12,Li12b,56013,Yes,244.551879,36.481075
23,SN 2012em,22 44 01.66,+15 51 49.3,91,0.0380,Be12 TD12,Mi12,56181,Yes,341.006917,15.863694
24,SN 2012fk,02 30 52.081,+22 28 46.02,Ia,0.0350,To12,Li12a,56223,Yes,37.717004,22.479450
25,SN 2013ar,08 37 45.02,+49 28 32.2,Ia,0.0600,ZJ13 To13c,Zh13c,56374,Yes,129.437583,49.475611
26,SN 2013bs,17 17 22.03,+41 04 00.2,Ia,0.0276,To13e,D13e,56403,Yes,259.341792,41.066722
27,SN 2013bt,14 21 15.185,+61 34 15.42,Ia,0.0364,To13f,D13f,56408,Yes,215.313271,61.570950
28,SN 2013cs,13 15 14.839,-17 57 55.24,Ia,0.0092,Y13,Ho13a,56436,Yes,198.811829,-17.965344
29,SN 2013fn,21 00 23.673,-14 29 52.42,Ia,0.0270,Mo13 MC13,Ho13b,56572,Yes,315.098637,-14.497894
30,iPTF13dkl,23 44 57.999,+03 23 40.07,Ia,0.0400,C13a,C13a,56556,Yes,356.241662,3.394464
31,iPTF13dkx,01 20 53.115,+03 20 23.65,Ia,0.0300,C13a,C13a,56561,Yes,20.221312,3.339903
32,iPTF13ebh,02 21 59.98,+33 16 13.7,Ia,0.0132,C13c,C13c,56619,Yes,35.499917,33.270472

In [12]:
SS_info["Name"] = SS_info["Name"].str.replace(" ","")

In [13]:
SS_info["Name"]

0     CSS121006:232854+085452
1     CSS121009:011101-172841
2     CSS121114:090202+101800
3                    LSQ12fhs
4                    LSQ12fmx
5                    LSQ13cmt
6                    LSQ13cwp
7                   PS1-13dkh
8                    PTF11moy
9                    PTF11qmo
10                   PTF11qri
11                   PTF13asv
12                   PTF13dad
13                   PTF13ddg
14                   SN2011fe
15                   SN2011fs
16                   SN2011gf
17                   SN2011io
18                   SN2011iy
19                   SN2011jh
20                   SN2012bh
21                   SN2012bo
22                   SN2012bp
23                   SN2012em
24                   SN2012fk
25                   SN2013ar
26                   SN2013bs
27                   SN2013bt
28                   SN2013cs
29                   SN2013fn
30                  iPTF13dkl
31                  iPTF13dkx
32                  iPTF13ebh
Name: Name, dtype: str

In [14]:
names = []
RAs = []
Decs = []
zs = []
LCs = []
for i, name in enumerate(SS_info["Name"]):
    names.append(name)
    RAs.append(SS_info["RA_deg"][i])
    Decs.append(SS_info["Dec_deg"][i])
    zs.append(SS_info["z"][i])
    LC0s = []
    print(i)
    for band in SS_LCs["Filter"]:
        LC_holder = []
        mags = []
        mag_errs = []
        mjd = []
        filtered = SS_LCs.loc[(SS_LCs["Name"]== name) & (SS_LCs["Filter"]== band)]
        #print(filtered.shape)
        if filtered.shape[0] == 0:
            continue
        #print(filtered["Mag"].index[0])
        for mag in filtered["Mag"]:
            #print(mag)
            mags.append(mag)
        for magerr in filtered["Mag Error"]:
            mag_errs.append(magerr)
        for date in filtered["MJD"]:
            mjd.append(date)
        LC_holder.append(mjd)
        LC_holder.append(mags)
        LC_holder.append(mag_errs)
        LC0s.append(band)
        LC0s.append(LC_holder)
    LCs.append(LC0s)
del LCs[0]

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32

In [15]:
print(len(LCs))

32